-- Project 1 - Load the PySpark-curated CSV exports from Amazon S3
-- Run this file after 01_snowflake_ddl.sql.

USE DATABASE RETAIL_PIPELINE_DB;


-- Confirm that Snowflake can see the four S3 export folders.
LIST @RAW.RETAIL_CURATED_S3_STAGE;


-- Make the script safe to rerun without duplicating previously loaded rows.
TRUNCATE TABLE CURATED.FACT_ORDERS;
TRUNCATE TABLE CURATED.DIM_CUSTOMERS;
TRUNCATE TABLE CURATED.DIM_PRODUCTS;
TRUNCATE TABLE DQ.DQ_SUMMARY;


COPY INTO CURATED.DIM_CUSTOMERS
FROM @RAW.RETAIL_CURATED_S3_STAGE/dim_customers/
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_WITH_HEADER_FORMAT')
PATTERN = '.*[.]csv([.]gz)?'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO CURATED.DIM_PRODUCTS
FROM @RAW.RETAIL_CURATED_S3_STAGE/dim_products/
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_WITH_HEADER_FORMAT')
PATTERN = '.*[.]csv([.]gz)?'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO CURATED.FACT_ORDERS
FROM @RAW.RETAIL_CURATED_S3_STAGE/fact_orders/
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_WITH_HEADER_FORMAT')
PATTERN = '.*[.]csv([.]gz)?'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO DQ.DQ_SUMMARY
FROM @RAW.RETAIL_CURATED_S3_STAGE/dq_summary/
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_WITH_HEADER_FORMAT')
PATTERN = '.*[.]csv([.]gz)?'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';
